services:
  nginx:
    image: nginx:latest
    container_name: slim_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./docker/dev/nginx:/etc/nginx/conf.d
      - ./docker/dev/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - php-fpm
    networks:
      - slim_network

  php-fpm:
    build:
      context: ./docker/dev/php-fpm
      dockerfile: Dockerfile
    container_name: slim_php-fpm
    volumes:
      - .:/var/www
    depends_on:
      - postgres
    networks:
      - slim_network

  php-cli:
    build:
      context: ./docker/dev/php-cli
      dockerfile: Dockerfile
    container_name: slim_php-cli
    volumes:
      - .:/var/www
    depends_on:
      - postgres
    networks:
      - slim_network
    tty: true

  postgres:
    image: postgis/postgis:15-3.4
    container_name: slim_postgres
    restart: always
    environment:
      POSTGRES_DB: slim_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - slim_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: slim_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - slim_network

volumes:
  postgres_data:
    driver: local

networks:
  slim_network:
    driver: bridge